[id="ccg-flat-file-structure_{context}"]
= Flat file structure

In a flat file structure, there are no sub-directories, just one directory with all the documentation files in a single directory.  A flat file structure might be as simple as a single README file, or contain a complete guide. A flat file structure for an AsciiDoc guide might look something like this:

....
├── README.adoc
├── documentation
├──|── master-docinfo.xml
├──|── master.adoc
├──|── attributes.adoc
├──|── logo.png
├──|── screenshot1.png
├──|── screenshot2.png
├──|── screenshot3.png
├──|── topic-1.adoc
├──|── topic-2.adoc
├──|── topic-4.adoc
├──|── topic-5.adoc
....

In a flat file system, every file must have a different name because there is only one list of files.  A flat file structure may work with a very small number of files, but once a documentation project becomes more complex, it becomes more difficult to have all the files in the same directory.  And that is when the documentation for a project may require a more complex structure.

