[id="ccg-asciidoc-attributes_{context}"]
= AsciiDoc attributes

AsciiDoc attributes are variables you can use in common files to:

* avoid hard-coding brand-specific information,
* share content between multiple brands more easily.

To use attributes:

. Set them in the relevant _brand_ AsciiDoc attribute file in the `common` directory.
. Include the _brand_ AsciiDoc attribute file in the `master.adoc` file for the relevant document:
+
[source,asciidoc]
----
\include::attributes.adoc[]
----
+
. Replace brand-specific terms with the variable names that you have defined, and use `ifdef` statements to mark blocks of brand-specific content.

Common AsciiDoc attributes include product name, abbreviated product name, and product version.
For more information about attributes  and `ifdef` statements, see http://asciidoctor.org/docs/user-manual/#attributes[Attributes^] and http://asciidoctor.org/docs/user-manual/#conditional-preprocessor-directives[Conditional Preprocessor Directives^] in the __Asciidoctor User Guide__.

The example below creates attributes for the *Community Documentation* brand.

. Create a new `community.adoc` file in the `common/attributes/` directory.

. Open the file, and add your attribute mappings, each entry on a new line:
+
[source,asciidoc]
----
:product-name: Community Documentation
:product-name_short: Community
:product-name_abbr: cd
:product-version: 1.0
----
+
. Save the file.
. In each `_doc-Guide_Name_/community` directory, edit the `master.adoc` file.
Include the attribute file, and add the variable name you want to use to identify `ifdef` statements:
+
[source,asciidoc]
----
\include::common/attributes/community.adoc[]

:community:
----
+
. Anywhere in a common topic file that you would normally use the product name or version, use the following values instead:
+
[source,asciidoc]
----
{product-name}
{product-name_short}
{product-name_abbr}
{product-version}
----
+
. Anywhere in a common topic file that you need a section of text to appear only in the *Community Documentation* version of the guide, use an `ifdef` statement:
+
[source,asciidoc]
----
// An ifdef for an entire sentence or paragraph
\ifdef::community[]
This is a sentence that applies only to the Community Documentation version of the document.
\endif::community[]

// An ifdef for an inline reference, which includes an entry for another brand
See
\ifdef::community[the Community Standards Guide.]
\ifdef::productx[the Product X Conventions Guide.]
----
+
The `ifdef` statement must be at the start of a new line, even for inline references.
When the *Community Documentation* version of the guide is rendered, the content inside the `ifdef` statements for `community` will appear, and the content inside the `ifdef` statements for `productx` will be excluded.
Any content not included inside an `ifdef` statement will appear in rendered guides for all brands.

. Render the guide to verify that your attributes are appearing correctly.
Navigate to the directory containing the `master.adoc`, and use:
+
----
asciidoctor compile
----

