[id="proposing-a-change-to-the-guide_{context}"]
= Proposing a change to the guide

Currently, the best method for proposing a change to the _Community Collaboration Guide_ is to open an issue in the https://github.com/redhat-documentation/community-collaboration-guide[community-collaboration-guide] GitHub repository.

.Prerequisites

You must be a member of the GitHub `community-collaboration-guide` repository. Request to join by emailing your GitHub username to ccs-upstream@redhat.com.

.Procedure

. Navigate to the https://github.com/redhat-documentation/community-collaboration-guide/issues[*Issues*] tab and click *New issue.* The window for creating a new issue is displayed.
. In the `Title` field, type a concise summary of the Guide change you are proposing.
. In the `Write` field, provide additional details, such as the "what, where, and why" of the modification.
. Attach any files, such as screen captures, that help illustrate your proposal.
. (Optional) Navigate to the `Preview` tab to review your submission.
. Click `Submit new issue`. The title and number of your open issue are displayed in a new window.

