[[ccg-contributing-to-the-framework]]
== Contributing to the Framework

You can contribute to this project in two ways:

* Propose changes to the template

* Update the _Community Collaboration Guide_

Subsequent sections provide details for conducting each activity.

[[ccg--proposing-a-change]]
=== Proposing a Change to the Template

Currently, the best method for proposing a change to the template is to open an issue in the https://github.com/redhat-documentation/community-contribution-template[community-contribution-template] GitHub repository.

.Prerequisites

You must be a member of the GitHub `community-contribution-template` repository.

.Procedure

. Navigate to the https://github.com/redhat-documentation/community-contribution-template/issues[*Issues*] tab and click *New issue.* The window for creating a new issue is displayed.

. In the `Title` field, type a concise summary of the template change you are proposing.

. In the `Write` field, provide additional details, such as the "what, where, and why" of the modification.

. Attach any files, such as screen captures, that help illustrate your proposal.

. (Optional) Navigate to the `Preview` tab to review your submission.

. Click `Submit new issue`. The title and number of your open issue are displayed in a new window.

[[ccg-updating-collaboration-guide]]
=== Updating the Community Collaboration Guide

We encourage contributions to the _Community Collaboration Guide_. In particular, you can share your experiences in the following areas:

* Evaluating communities

* Working through the communications process

* Using supported (and unsupported) tools

* Structuring repositories in new and different ways

* Exploring best practices and discovering lessons learned

.Prerequisites

* You must have downloaded, installed, and configured Git on your desktop.

* Ensure that your configuration gives you the ability to manage files locally by using the command line.

.Related Information

https://help.github.com/articles/set-up-git/[Set Up Git]

[discrete]
[[ccg-fork-the-upstream-repository]]
=== Fork the Upstream (GitHub) Repository

Fork the `community-contribution-template` upstream repository to create a fork under your own GitHub ID. This allows you to work on multiple pieces of content and push changes to branches in your local GitHub instance. When you are ready, you can request the changes be merged from your local fork into the upstream repository.

. Open a browser and navigate to the upstream repository located at https://github.com/redhat-documentation/community-contribution-template[https://github.com/redhat-documentation/community-contribution-template].

. Click the *Fork* button located in the upper right, under your profile icon.

. Choose the location of the forked repository.

[discrete]
[[ccg-add-ssh-keys]]
=== Add Your SSH Keys to GitHub

When using the SSH address for creating a clone, you need to add an SSH Key to GitHub. See the article https://help.github.com/articles/connecting-to-github-with-ssh/[_Generating an SSH Key_] for more information.

[discrete]
[[ccg-clone-upstream-repository]]
=== Clone the Upstream Repository to Your Fork

Clone the repository. Your fork is the `origin` location for your local files.

. Open a terminal and navigate to the location where you want to create a directory to contain your local copy of the repository.

. Type the following command:
[options="nowrap",subs="+quotes"]
----
$ git clone git@github.com:USERNAME/community-contribution-template.git
----
In this and subsequent examples, _USERNAME_ represents your GitHub User ID.

[start=3]
. Navigate to the newly created `community-contribution-template` directory.
[options="nowrap",subs="+quotes"]
----
$ cd community-contribution-template/
----

[discrete]
[[ccg-add-upstream-remote]]
=== Add the Upstream as a Remote Repository

After you have forked and cloned the upstream repository, connect it to your local fork by adding the upstream repository as a remote.

. List the current remote repositories:
[options="nowrap",subs="+quotes"]
----
$ git remote -v
origin	git@github.com:USERNAME/community-contribution-template.git (fetch)
origin	git@github.com:USERNAME/community-contribution-template.git (push)
----

[start=2]
. Add the upstream as a remote repository and fetch its contents. This allows you to check out and work with the latest source.
[options="nowrap",subs="+quotes"]
----
$ git remote add -f upstream git@github.com:redhat-documentation/community-contribution-template.git
----

[start=3]
. Enter your GitHub credentials if prompted to do so.

. Verify that the new remote was added:
[options="nowrap",subs="+quotes"]
----
$ git remote -v
origin	git@github.com:USERNAME/community-contribution-template.git (fetch)
origin	git@github.com:USERNAME/community-contribution-template.git  (push)
upstream	git@github.com:redhat-documentation/community-contribution-template.git (fetch)
upstream	git@github.com:redhat-documentation/community-contribution-template.git (push)
----

[discrete]
[[ccg-fetch-source-create-branch]]
=== Fetch the Source and Create a Branch

Fetch the latest source from the upstream repository. Note that using the `git fetch` command to obtain the latest copy of the source does not actually "put" the content on your local fork until you perform some other action, such as creating a branch.

. Use the `git fetch` command to fetch the latest source from the repository.
[options="nowrap",subs="+quotes"]
----
$ git fetch upstream
----
[start=2]
. Create a local working branch that is based on an upstream branch. The branch name should be descriptive, containing an issue number or short summary of the change.
[options="nowrap",subs="+quotes"]
----
$ git checkout -b BRANCH_NAME upstream/master
----
In this example, _BRANCH_NAME_ is the unique name of the branch you are using to make changes locally.

[NOTE]
====
You can check out multiple topic branches and work on multiple features at one time, with no impact on each other as long as each topic branch is branched from `master`.
