== Introduction

This communication survey is to be used by CCS to determine if single-streaming documentation is feasible on a specific project. Content Strategists and Documentation Program Managers will work together to gather data to evaluate community documentation for their products. Using the results of this survey the CCS team will make a proposal for or against single-streaming documentation.

=== Overview

Customer Content Services (CCS) is responsible for producing documentation for Red Hat customers. Since all Red Hat products have an upstream, or open source community version, it makes sense for CCS to use these upstream resources in developing guides for customers. Many programs will use pieces of upstream content in the downstream documentation. This framework will define best practices for single-streaming your documentation.

Single-streamed documentation will be worked on completely in the upstream and then brought down to the customer portal wholesale. In some projects this process will eliminate the additional overhead of maintaining two separate repositories for documentation content.  This framework will guide you through the process necessary for deciding if a community is a viable single-stream partner, setting up your repositories, choosing the right tools, and more.
