== Structure

When building a new repo, one can choose a single title per repository or multiple titles per repository structure. Contribution style and build requirements are two primary considerations.
The single title per repository model allows independent updates between titles, but prevents topic sharing among titles.
The multiple title per repository model enables simple-and-easy topic-sharing between titles, but does require building all
titles when updates are made.

=== Directory Structure

Directories should be structured in a logical and related fashion. Folder and document names should be clear and consistent; "52187.adoc" is not likely to mean anything to anyone save the author.

Here is an example directory structure of a single title per repository structure.

----
*GUIDE_NAME/* _(The specific book)
.
├──├── *images/*  _(Contains all the images used by the docs)_
├──│   │   ├── my-image.png
├──├──*topics/*  _(Folder that contains all AsciiDoc topic files)_
├──│   ├── *templates/*  _(AsciiDoc template files to be used across guides)_
├──│   ├──*topic_focus_1 _(folder to hold related topics; repeat for each topic focus)_
├──│   ├──├── topic_focus_a.adoc _(AsciiDoc file for information within each focus area; repeat as needed)_
├──*README.adoc*  _(This file)_
├──*master.adoc*  _(Top level content specification for the book)_
├──*document-attributes.adoc*  _(Document attributes used across guides)_
└──*buildGuide.sh*  _(Script to build this book)_
----
Here is an example directory structure of a multiple titles per repository structure.
----
.
├── *README.adoc*  _(This file)_
├── *docs/*  _(Contains the book folders and topics folder)_
│   ├── *GUIDE_NAME/*  _(Book folder; repeat for each title in the repository)_
│   │   ├── *master.adoc*  _(Top level content specification for the book)_
│   │   ├── *buildGuide.sh*  _(Script to build this book)_
│   │   ├── *topics*  _(Symbolic link to docs/topics/)_
│   ├── *topics/*  _(Folder that contains all AsciiDoc topic files)_
│   │   │   ├── *images/*  _(Contains all the images used by the docs)_
│   │   │   │   ├── my-image.png
│   │   │   ├── *templates/*  _(AsciiDoc template files to be used across guides)_
│   │   │   │   ├── *document-attributes.adoc*  _(Document attributes used across guides)_
│   │   │   ├── my-topic.adoc
├── *internal-resources/*  _(References for contributors)_
├── *legacy-topics/*  _(Houses any legacy source)_
│   ├── *asciidoc/*  _(Houses any converted AsciiDoc files)_
│   └── *docbook-xml/*  _(Houses any DocBook XML topics from previous sources)_
└── *scripts/*  _(Contains scripts that automate the processes used to create and build documentation)_
    ├── *buildGuides.sh*  _(Builds all top-level guides that live in the docs/ folder)_
    └── *processPrevSourceTopics.sh*  _(Retrieves files from a previous source, converts them to AsciiDoc, the stores them in the legacy-topics folder)_
----


=== AsciiDoc Attributes

AsciiDoc attributes are variables you can use in common files to avoid hard-coding brand-specific information. Using attributes allows you to more easily share content between multiple brands. To use attributes, first define them in the relevant _brand_ AsciiDoc attribute file in the `common` directory. Then, include the _brand_ AsciiDoc attribute file in the `master.adoc` file for the relevant document. Finally, replace brand-specific terms with the variable names that you have defined, and use `ifdef` statements to indicate mark blocks of brand-specific content.

Common AsciiDoc attributes include product name, abbreviated product name, and product version. For more information about attributes  and `ifdef` statements, see http://www.methods.co.nz/asciidoc/userguide.html#X18[Attribute Entries] and http://www.methods.co.nz/asciidoc/userguide.html#_conditional_inclusion_macros[Conditional Inclusion Macros] in the __AsciiDoc User Guide__.

The example below creates attributes for the *Community Documentation* brand.

. Create a new `community.adoc` file in the `common/attributes/` directory.

. Open the file, and add your attribute mappings, each entry on a new line:
+
----
:product-name: Community Documentation
:product-name_short: Community
:product-name_abbr: cd
:product-version: 1.0
----
+
. Save the file.
. In each _doc-Guide_Name_/`community` directory, edit the `master.adoc` file. Include the attribute file, and add the variable name you want to use to identify `ifdef` statements:
+
----
include::common/attributes/community.adoc

:community:
----
+
. Anywhere in a common topic file that you would normally use the product name or version, use the following values instead:
+
----
{product-name}
{product-name_short}
{product-name_abbr}
{product-version}
----
+
. Anywhere in a common topic file that you need a section of text to appear only in the *Community Documentation* version of the guide, use an ifdef statement:
+
----
// An ifdef for an entire sentence or paragraph
 ifdef::community[]
 This is a sentence that applies only to the Community Documentation version of the document.
 endif::community[]

// An ifdef for an inline reference, which includes an entry for another brand
 See
 ifdef::community[the Community Standards Guide.]
 ifdef::productx[the Product X Conventions Guide.]
----
+

The `ifdef` statement must be at the start of a new line, even for inline references. When the *Community Documentation* version of the guide is rendered, the content inside the `ifdef` statements for `community` will appear, and the content inside the `ifdef` statements for `productx` will be excluded. Any content not included inside an `ifdef` statement will appear in rendered guides for all brands.

. Render the guide to verify that your attributes are appearing correctly.

=== Rendering Content

Placeholder text.

=== Synchronizing Content

Placeholder text.

=== Publishing Content

Placeholder text.

==== AsciiBinder

Placeholder text.

Reference::https://placeholder.url[]

==== RPM Packaging

Placeholder text.

Reference::https://placeholder.url[]

==== Microservices

Placeholder text.

Reference::https://placeholder.url[]

==== Other

Placeholder text.
