[[project_structure]]
== Project Structure 

There is no single structure that will work for all projects, rather as a project grows and becomes more complex, it is likely to move through a variety of different structures.  The repository structure may change as files and directories are added, a large repository may split into separate, related repositories, etc.    As a project grows, the documentation needs for the project also grow. And just like you want to have a plan for project architecture that changes and adapts as the project grows, you likewise want to have a plan for the documentation structure that grows and adapts as the doc set grows.

This section discusses repository and directory structure and how to structure your content for ease of reuse (both in multiple documents and in upstream/downstream documents).


[[directory_structure]]
=== Directory Structure

The first steps towards documenting a project are often found in the README file of the repository.   Eventually the project will grow to where there is a need for more documentation than you can fit in a single README, and that may appear in the form of a project wiki, a separate installation guide, possibly a developer guide, and one or more user guides.   You may start out with all of the documentation in the same repository as the code, but as things grow more complex, you may want to consider having a separate repository for your documentation.  This makes it easier for community members who may only want to contribute to the documentation, as they don’t have to worry about merge conflicts in the code.

As your project grows, you should consider the structure you want to use for your documentation directory.  Directories should be structured in a logical and related fashion. Many projects have a documentation repo or folder for their project web page, and possibly a separate repo or folder for the project documentation.  You may choose to have separate repositories for each “manual” or you may choose to have all the documents in your doc set share a repository.  Contribution style and build requirements are two primary considerations when you decide how to proceed.

* Add a docs folder to the code repository.  This makes it easier for developers to update the documentation, but may present a challenge for non-developers who want to contribute to the documentation but may not know now to resolve merge conflicts in the code.
* Add a new repo for each new title or document. The single title per repository model allows independent updates between titles, but prevents topic sharing among titles. 
* Add a new repo with multiple titles or documents. The multiple title per repository model enables simple-and-easy topic-sharing between titles, but does require building all titles when updates are made.

[[flat_file_structure]]
=== Flat File Structure

In a flat-file structure there are no sub-directories, just one folder with all the documentation files in a single directory.  A flat file structure might be as simple as a single README file, or contain a complete manual. A flat file structure for an asciidoc manual might look something like this:

....
├── README.adoc
├── documentation
├──|── master-docinfo.xml
├──|── master.adoc
├──|── attributes.adoc
├──|── logo.png
├──|── screenshot1.png
├──|── screenshot2.png
├──|── screenshot3.png
├──|── topic-1.adoc
├──|── topic-2.adoc
├──|── topic-4.adoc
├──|── topic-5.adoc
....

In a flat file system every file must have a different name because there is only one list of files.  A flat file structure may work with a very small number of files, but once a documentation project becomes more complex, it becomes more difficult to have all the files in the same directory.  And that is when the documentation for project may require a more complex structure.


[[single_book_structure]]
=== Single Book Structure

If you do not share any content between books you may choose a single book per directory structure.  A structure with a single asciidoc manual per repository might look something like this:

....
├── README.adoc
├── docs
│   ├── DocumentTitle
│   ├──-|──  topics -> ../topics/ (symlink to docs/topics/)
│   ├──-|── master-docinfo.xml
│   ├──-|── master.adoc   (book file/table of contents for the documentation)
│   │   ├── /topics  (all topic files for the documentation)
│   │   │   ├──  /images (all images for the documentation)
│   │   │   │    ├── logo.png
│   │   │   │    ├──screenshot1.png
│   │   │   │    ├── screenshot2.png
│   │   │   │    ├──screenshot3.png
│   │   │   ├── attributes.adoc (variables file)
│   │   │   ├── topic-1.adoc
│   │   │   ├── topic-2.adoc
│   │   │   ├── topic-4.adoc
│   │   │   └── topic-5.adoc
└── scripts (Scripts to automatically create and build documentation)
    └── buildGuides.sh 
....


[[multiple_book_structure]]
=== Multiple Book Structure
If you have common files that you want to reuse between books, you may choose a more complex directory structure, where all the books live in the same repository and have access to common files.   

Note that in the following multiple book structure each “book” directory has a symlink to a common directory for topic files.  This allows you to use any individual topic in any book, saving time writing and updating topics that appear in more than one place.  This structure also uses a common folder for images inside the topics folder, again allowing for reuse of images such as button icons and product logos.  And the attributes file is also common, allowing for the same replacement variables in all files and books.

A structure with multiple asciidoc manuals per repository and a single topic directory might look something like this:
////
internal Up/Down repo template on Red Hat GitLab https://gitlab.cee.redhat.com/ccs-tools-documentation/up-down-repo-template#use-this-repository-template
////
....
├── README.md 
├── docs 
│   ├── Title_A
│   │   ├── master.adoc
│   │   ├── master-docinfo.xml
│   │   ├── topics -> ../topics/ (symlink to docs/topics/)
│   ├── Title_B
│   │   ├── master.adoc
│   │   ├── master-docinfo.xml
│   │   ├── topics -> ../topics/ (symlink to docs/topics/)
│   ├── Title_C
│   │   ├── master.adoc
│   │   ├── master-docinfo.xml
│   │   ├── topics -> ../topics/ (symlink to docs/topics/)
│   ├── topics (all topics for titles)
│   │   │   ├── images (all the images for titles)
│   │   │   |   ├──  logo.png
│   │   │   |   ├──  screenshot1.png
│   │   │   |   ├── screenshot2.png
│   │   │   |   ├── screenshot3.png
│   │   │   ├──attributes.adoc (variables file)
│   │   │   ├── topic-1.adoc
│   │   │   ├── topic-2.adoc
│   │   │   ├── topic-4.adoc
│   │   │   └── topic-5.adoc
│   │   │   ├── topic-shared-1.adoc
│   │   │   ├──  topic-shared-2.adoc
....

And a structure with multiple asciidoc manuals per repository and multiple topic directories might look something like this:
////
Silas’s Multi-topic repo template on GitHub
https://github.com/silasrh/multi-topic-level-repo-template
////
....
├── README.adoc
├── docs
│   ├── title-a
│   │   ├── enterprise
│   │   │   ├── master-docinfo.xml
│   │   │   ├── master.adoc
│   │   │   └── topics -> ../topics
│   │   ├── topics
│   │   │   ├── shared -> ../../shared
│   │   │   ├── topic-1.adoc
│   │   │   ├── topic-2.adoc
│   │   │   ├── topic-4.adoc
│   │   │   └── topic-5.adoc
│   │   └── upstream-1
│   │       ├── master-docinfo.xml
│   │       ├── master.adoc
│   │       └── topics -> ../topics
│   ├── title-b
│   │   ├── enterprise
│   │   │   ├── master-docinfo.xml
│   │   │   ├── master.adoc
│   │   │   └── topics -> ../topics
│   │   ├── topics
│   │   │   ├── shared -> ../../shared
│   │   │   ├── topic-1.adoc
│   │   │   ├── topic-2.adoc
│   │   │   ├── topic-4.adoc
│   │   │   └── topic-5.adoc
│   │   └── upstream-1
│   │       ├── master-docinfo.xml
│   │       ├── master.adoc
│   │       └── topics -> ../topics
│   └── shared
│       ├── attributes.adoc (variables file)
│       ├── images (all images for titles)
│       ├── templates
│       │   └── revision-info.adoc
│       ├── topic-shared-1.adoc
│       └── topic-shared-2.adoc
└── resources
    ├── asciidoc-writing-guide.adoc
    └── scripts
        └── buildGuides.sh
....


[[content_structure]]
=== Content Structure 
Rather than writing your documentation in a single lengthy file, a best practice is to break the content up into small chunks.  There are several reasons why this is a good idea.   Having some sort of structure for your content provides many benefits for both readers and writers of your documentation:

* *Onboarding new contributors* – It’s easier for new contributors to add to the documentation if they have some sort of template or pattern to follow. For example, all 	UNIX/LINUX man pages follow a similar structure, so when a developer is documenting a new command, they can follow that familiar pattern.
+
A commonly used pattern for documentation is to chunk content into one of three types of topics:
+
** *Procedure or Task* – The ordered steps to complete a task or perform an action using the software.

** *Concept or Overview* – Product specific terminology or concepts that the user needs to understand in order to successfully use the software.
** *Reference* – Reference material about the software, for example configuration settings , lists of commands, or API documentation.

* *Reusability* – If you write content in small chunks, it can be reused in different documents that cover the same topics. For example, topics such as “System Requirements” or “Supported Platforms” might appear in Release Notes, planning documentation, and installation documentation. 
* *Findability* – Content that is properly structured makes it easier for readers to find answers to their 	questions. For example, when procedures are properly formatted as	numbered steps, readers don’t have to search paragraphs of text for instructions for how to complete a task. Projects that follow naming conventions and have an organizational structure make it easier for contributing writers to find and update topics.
* *Organization* – Writing content in small chunks makes it easier to rearrange content than writing content in longer files.  

In general when writing content you want to use simple language and avoid jargon that people unfamiliar with your project might not understand  Writing short sentences and short paragraphs also makes your content easier to read and understand.


[[file_naming]]
=== File Naming

No matter what repo and directory structure you choose, folder and file names should be clear and consistent.  

* Numbered file names like "52187.adoc" or “IMG_390.png” are more likely to cause confusion for other contributors.
* Short file names are good, as long as they're still meaningful.  But give enough detail to make the content clear (“overview.adoc” could be anything).
* Long file names are often unwieldy, hard to work with, and easy to mistype.  Try to find the right balance for file name length.
* File names should reflect the topic they cover to help contributors find content in your files.
* Do not include the project or product name, book name, release version, or anything similar in file names.
* Do not hard code file names when linking documents, use  relative paths to the topic or folder.




[[asciidoc_converter]]
=== Asciidoc Converters

If your project is not already written in Asciidoc and you want to migrate from markdown or another markup language, there are a variety of conversion tools available.

* The Atom editor has a https://atom.io/packages/markdown-to-asciidoc[package to convert markdown to asciidoc].

* There is a plugin to https://chrome.google.com/webstore/detail/asciidoc-processor/eghlmnhjljbjodpeehjjcgfcjegcfbhk?hl=en[convert Google docs to asciidoc].

* https://pandoc.org/[Pandoc] can convert between a large number of different markup and file formats including DocBook, Emacs Org-Mode, EPUB, HTML, LaTeX, LibreOffice ODT, markdown, MediaWiki markup, Microsoft Word docx, OPML, reStructuredText, textile, TWiki markup, and Txt2Tags.


[[asciidoc_attributes]] 
=== AsciiDoc Attributes

AsciiDoc attributes are variables you can use in common files to avoid hard-coding brand-specific information. Using attributes allows you to more easily share content between multiple brands. To use attributes, first define them in the relevant _brand_ AsciiDoc attribute file in the `common` directory. Then, include the _brand_ AsciiDoc attribute file in the `master.adoc` file for the relevant document. Finally, replace brand-specific terms with the variable names that you have defined, and use `ifdef` statements to indicate mark blocks of brand-specific content.

Common AsciiDoc attributes include product name, abbreviated product name, and product version. For more information about attributes  and `ifdef` statements, see http://www.methods.co.nz/asciidoc/userguide.html#X18[Attribute Entries] and http://www.methods.co.nz/asciidoc/userguide.html#_conditional_inclusion_macros[Conditional Inclusion Macros] in the __AsciiDoc User Guide__.

The example below creates attributes for the *Community Documentation* brand.

. Create a new `community.adoc` file in the `common/attributes/` directory.

. Open the file, and add your attribute mappings, each entry on a new line:
+
----
:product-name: Community Documentation
:product-name_short: Community
:product-name_abbr: cd
:product-version: 1.0
----
+
. Save the file.
. In each _doc-Guide_Name_/`community` directory, edit the `master.adoc` file. Include the attribute file, and add the variable name you want to use to identify `ifdef` statements:
+
----
include::common/attributes/community.adoc

:community:
----
+
. Anywhere in a common topic file that you would normally use the product name or version, use the following values instead:
+
----
{product-name}
{product-name_short}
{product-name_abbr}
{product-version}
----
+
. Anywhere in a common topic file that you need a section of text to appear only in the *Community Documentation* version of the guide, use an ifdef statement:
+
----
// An ifdef for an entire sentence or paragraph
 ifdef::community[]
 This is a sentence that applies only to the Community Documentation version of the document.
 endif::community[]

// An ifdef for an inline reference, which includes an entry for another brand
 See
 ifdef::community[the Community Standards Guide.]
 ifdef::productx[the Product X Conventions Guide.]
----
+

The `ifdef` statement must be at the start of a new line, even for inline references. When the *Community Documentation* version of the guide is rendered, the content inside the `ifdef` statements for `community` will appear, and the content inside the `ifdef` statements for `productx` will be excluded. Any content not included inside an `ifdef` statement will appear in rendered guides for all brands.

. Render the guide to verify that your attributes are appearing correctly.


[[rendering_content]]
=== Rendering Content

ifdef::community[]
When your source content is ready to be reviewed or published, you can render it into a display format that can be hosted on a website, included directly in a product, or otherwise accessed by your users. The recommended tool for rendering AsciiDoc into a display format is AsciiDoctor. AsciiDoctor is a fully open-source, Ruby-based implementation of AsciiDoc, and is also the tool that GitHub itself uses to render the content of files written in AsciiDoc.

See the project home page for instructions on how to install AsciiDoctor on a variety of platforms:

* http://asciidoctor.org/

The following is the basic syntax for rendering content into a display format:

[options="nowrap" subs="verbatim,quotes"]
----
$ asciidoctor master.adoc
----

This command creates a single HTML file of the same name and in the same directory as the specified master file. The master file does not need to be in the current working directory, and you can specify either a relative path or absolute path to it.

In addition to this basic syntax, AsciiDoctor also provides a number of options that allow you to customize the location and format of the content that it renders.

The following example outlines how to specify a custom output directory:

[options="nowrap" subs="verbatim,quotes"]
----
$ asciidoctor -D ./output master.adoc
----

The following example outlines how to render the content as an article instead of as a book:

[options="nowrap" subs="verbatim,quotes"]
----
$ asciidoctor -d article master.adoc
----

For additional examples, including instructions on how to render content in formats other than HTML such as PDF, EPUB3, and LaTeX, see link:http://asciidoctor.org/docs/render-documents/[How do I render a document?] on the AsciiDoctor project home page. 
endif::community[]

ifdef::redhat[]
You can use `ccutil` to build a local preview of your content in the same way as repositories that do not use this repository structure. The only difference is that the command must be run in the `redhat` brand directory where the master file is located instead of in the default content directory. Pantheon builds and build scripts must also be updated to specify the `redhat` brand directory.
endif::redhat[]

[[synchronizing_content]]
=== Synchronizing Content

Placeholder text.

[[publishing_content]]
=== Publishing Content

Placeholder text.


[[asciibinder]]
==== AsciiBinder

Placeholder text.

Reference::https://placeholder.url[]


[[rpm_packaging]]
==== RPM Packaging

Placeholder text.

Reference::https://placeholder.url[]


[[microservices]]
==== Microservices

Placeholder text.

Reference::https://placeholder.url[]

[[github_pages]]
==== GitHub Pages

Placeholder text.

Reference::https://placeholder.url[]

[[other]]
==== Other

Placeholder text.

