[#asciidoc]
== AsciiDoc
http://asciidoc.org/[AsciiDoc^] is a text document format that you can use to write documentation, articles, books, web pages, and blogs.
AsciiDoc files can be translated to many formats including HTML, PDF, EPUB, and man page.

The Red Hat documentation team uses http://asciidoctor.org/[Asciidoctor^] as part of the publishing toolchain.

[#ccg-asciidoc-attributes]
=== AsciiDoc attributes

AsciiDoc attributes are variables you can use in common files to:

* avoid hard-coding brand-specific information,
* share content between multiple brands more easily.

To use attributes:

. Set them in the relevant _brand_ AsciiDoc attribute file in the `common` directory.
. Include the _brand_ AsciiDoc attribute file in the `master.adoc` file for the relevant document:
+
[source,asciidoc]
--
\include::attributes.adoc[]
--
+
. Replace brand-specific terms with the variable names that you have defined, and use `ifdef` statements to mark blocks of brand-specific content.

Common AsciiDoc attributes include product name, abbreviated product name, and product version.
For more information about attributes  and `ifdef` statements, see http://asciidoctor.org/docs/user-manual/#attributes[Attributes^] and http://asciidoctor.org/docs/user-manual/#conditional-preprocessor-directives[Conditional Preprocessor Directives^] in the __Asciidoctor User Guide__.

The example below creates attributes for the *Community Documentation* brand.

. Create a new `community.adoc` file in the `common/attributes/` directory.

. Open the file, and add your attribute mappings, each entry on a new line:
+
----
:product-name: Community Documentation
:product-name_short: Community
:product-name_abbr: cd
:product-version: 1.0
----
+
. Save the file.
. In each `_doc-Guide_Name_/community` directory, edit the `master.adoc` file.
Include the attribute file, and add the variable name you want to use to identify `ifdef` statements:
+
----
include::common/attributes/community.adoc

:community:
----
+
. Anywhere in a common topic file that you would normally use the product name or version, use the following values instead:
+
----
{product-name}
{product-name_short}
{product-name_abbr}
{product-version}
----
+
. Anywhere in a common topic file that you need a section of text to appear only in the *Community Documentation* version of the guide, use an ifdef statement:
+
----
// An ifdef for an entire sentence or paragraph
 ifdef::community[]
 This is a sentence that applies only to the Community Documentation version of the document.
 endif::community[]

// An ifdef for an inline reference, which includes an entry for another brand
 See
 ifdef::community[the Community Standards Guide.]
 ifdef::productx[the Product X Conventions Guide.]
----
+

The `ifdef` statement must be at the start of a new line, even for inline references.
When the *Community Documentation* version of the guide is rendered, the content inside the `ifdef` statements for `community` will appear, and the content inside the `ifdef` statements for `productx` will be excluded.
Any content not included inside an `ifdef` statement will appear in rendered guides for all brands.

. Render the guide to verify that your attributes are appearing correctly.
Navigate to the directory containing the `master.adoc`, and use:
+
[source,bash]
--
asciidoctor compile
--

[#ccg-attributes-to-links]
=== Single-sourcing URLs using attributes

In addition to storing product names and versions, attributes can be used to store book-local and cross-book links for your guides.
Doing this allows you to:

* construct consistently structured and predictable link URLs (especially when combined with explicit ID anchors),
* single-source your link URLs, making updates easier,
* eliminate the risk of introducing errors when updating your links.

To store a relative link as an attribute, you must define it in the:

[source,asciidoc,option="nowrap"]
--
:link-getting-started: /docs/getting-strated.html
--
//Next step: Specify the variable in a link macro.

Attributes can also store external link URLs, allowing you to update them without breaking any links in your guide.

[source,asciidoc,options="nowrap"]
--
:link-community-docs: https://docs.example.com/guides/community.html
--

Use the variable in a link macro.
The variable will automatically resolve to the URL stored in the attribute when you build your documents.

[source,asciidoc,options="nowrap",subs="attributes+"]
--
link:{link-community-docs}#introduction[Community Documentation Introduction]
--

To force your links to open in a new window:

. Set the `linkattrs` attribute in your `attributes.adoc` file:
+
[source,asciidoc]
--
:linkattrs:
--
+
. Use the caret `^` character to enforce the `target=_blank` HTML attribute for the link anchor.
+
[source,asciidoc,options="nowrap",subs="attributes+"]
--
link:{link-community-docs}[Community Documentation^]
--
+
. Alternatively, you can set the the AsciiDoc attribute explicitly:
+
[source,asciidoc,options="nowrap",subs="attributes+"]
--
link:{link-community-docs}[Community Documentation, window="_blank"]
--
+
When clicked, the link will always open in a new tab.

// link:view-source:asciidoctor.org[Asciidoctor homepage,]

[#ccg-previewing-your-content]
=== Previewing your content

* The AsciiDoctor documentation has a chapter on link:http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/[Editing AsciiDoc with live preview^].

* The Atom editor has a link:https://atom.io/packages/asciidoc-preview[package to render a live preview^] of your AsciiDoc source, which allows you to see your markup rendered as you type it.

[#ccg-asciidoc-converter]
=== AsciiDoc converters

If your project is not already written in AsciiDoc and you want to migrate from Markdown or another markup language, there are a variety of conversion tools available.

* The Atom editor has a https://atom.io/packages/markdown-to-asciidoc[package to convert Markdown to AsciiDoc^].

* There is a plugin to https://chrome.google.com/webstore/detail/asciidoc-processor/eghlmnhjljbjodpeehjjcgfcjegcfbhk?hl=en[convert Google docs to AsciiDoc^].

* https://pandoc.org/[Pandoc^] can convert between a large number of different markup and file formats including DocBook, Emacs Org-Mode, EPUB, HTML, LaTeX, LibreOffice ODT, Markdown, MediaWiki markup, Microsoft Word docx, OPML, reStructuredText, textile, TWiki markup, and Txt2Tags.

* https://github.com/lruzicka/rst2adoc/[rst2adoc^] is an AsciiDoc builder and writer for Sphinx that allows you to convert reStructuredText (RST) files to AsciiDoc using the Sphinx build system.
