[[ccg-building-content]]
== Building content

Writing your documentation using AsciiDoc means that you can build HTML, PDF, EPUB, and man pages. During the writing process, you build your documentation to test and review the content as described in xref:ccg-rendering-content-locally[].

Depending on the complexity of the documentation, you might also decide to adopt a tool other than AsciiDoctor to help you organize the building of documentation sets. Some commonly used tools are described later in this section.

[[ccg-rendering-content-locally]]
=== Rendering content locally with AsciiDoctor

ifdef::community[]
When your source content is ready to be reviewed or published, you can render it into a display format that can be hosted on a website, included directly in a product, or otherwise accessed by your users. The recommended tool for rendering AsciiDoc into a display format is AsciiDoctor. AsciiDoctor is a fully open-source, Ruby-based implementation of AsciiDoc, and is also the tool that GitHub itself uses to render the content of files written in AsciiDoc.

See the project home page for instructions on how to install AsciiDoctor on a variety of platforms:

* http://asciidoctor.org/[http://asciidoctor.org/^]

The following is the basic syntax for rendering content into a display format:

[options="nowrap" subs="verbatim,quotes"]
----
$ asciidoctor master.adoc
----

This command creates a single HTML file of the same name and in the same directory as the specified master file. The master file does not need to be in the current working directory, and you can specify either a relative path or absolute path to it.

In addition to this basic syntax, AsciiDoctor also provides a number of options that allow you to customize the location and format of the content that it renders.

The following example outlines how to specify a custom output directory:

[options="nowrap" subs="verbatim,quotes"]
----
$ asciidoctor -D ./output master.adoc
----

The following example outlines how to render the content as an article instead of as a book:

[options="nowrap" subs="verbatim,quotes"]
----
$ asciidoctor -d article master.adoc
----

For additional examples, including instructions on how to render content in formats other than HTML such as PDF, EPUB3, and LaTeX, see link:http://asciidoctor.org/docs/render-documents/[How do I render a document?^] on the AsciiDoctor project home page.
endif::community[]

ifdef::redhat[]
You can use `ccutil` to build a local preview of your content in the same way as repositories that do not use this repository structure. The only difference is that the command must be run in the `redhat` brand directory where the master file is located instead of in the default content directory. Pantheon builds and build scripts must also be updated to specify the `redhat` brand directory.
endif::redhat[]

[[ccg-asciibinder-tool]]
=== AsciiBinder

AsciiBinder is a Ruby-based command-line tool that is designed to streamline the documentation and publication process for teams that manage a large volume of content and re-publish that content regularly. AsciiBinder allows you to share content across multiple distributions by using a map of content that is common to all distributions and by breaking the metadata for each distribution out into a separate branch in Git.

Website: link:http://www.asciibinder.org[http://www.asciibinder.org^]

Advantages::
* Stable
* Simple to use
* Low barrier to entry

Challenges::
* Support is provided on an ad-hoc basis
* Uses a fixed directory structure defined by AsciiBinder

[[ccg-gitbook-tool]]
=== GitBook

GitBook is a documentation hosting system based on GitHub.

Website: link:https://www.gitbook.com[https://www.gitbook.com^]

Advantages::
* Very low barrier to entry for community members
** Easy to make edits
** Comes with a built-in stylesheet
* Publishes in AsciiDoc
* Integrates into GitHub
* Allows inline comments
* Supports building books written in multiple languages
** Each language is in a subdirectory
** Support for rtl languages
* Includes a full-text search engine
** JSON index file on a static version of the documentation

Challenges::
* Having to review inline comments is time consuming when you are also monitoring issue tracking systems
* Converting to downstream requires a Python script
* Requires a lengthy process to pull content from GitBook to the downstream
* Directory tree defined by GitBook and does not allow for easy manipulation
* Only free for a small number of managers, has a cost after that
* Things that work in AsciiDoc do not always work in GitBook
** Certain special tags will completely break things in GitBook
** AsciiDoc is not fully supported in GitBook
* GitBook requires that we use a JSON file for attributes which is not as flexible as AsciiDoc
** You can embed attributes in AsciiDoc, but not in JSON
* GitBook support is ad-hoc
* Edits are immediately committed
* Editor is not advanced enough to keep in conditional tags in place

[[ccg-rst-sphinx-tool]]
=== RST with Sphinx

http://docutils.sourceforge.net/rst.html[reStructuredText (RST)^] is a popular lightweight documentation format used by many, particularly Python-based, projects and open source communities. RST is often used alongside the http://www.sphinx-doc.org/[Sphinx documentation generator^], which can be seen as an counterpart of the AsciiDoctor toolchain for AsciiDoc.

Advantages::
* The toolchain of choice for a large number of open source projects.
** Easy to find community support, resources and examples.
* Supports translations with gettext, has been integrated with http://zanata.org/[Zanata^].
* Supports multiple output formats, including HTML, HTML single, PDF, ePub, Texinfo, man pages, etc.
* Fully customized document hierarchy, design themes, etc.
* More features can be added with custom extensions.
* Supported by popular community hosting services, such as https://readthedocs.org/[Read the Docs^].

Challenges::
* Does not provide native integration with AsciiDoc-based toolchains.
** Extensions or converters must be used to build or convert RST to AsciiDoc. For details, see xref:ccg-asciidoc-converter[].
