[[ccg-introduction]]
== Introduction

This guide has been provided by https://www.redhat.com/[Red Hat^] to assist enterprise projects in collaborating with upstream communities on documentation. For Red Hat, this guide provides tips for evaluating a community to see if they are prepared for collaboration with an enterprise software team, communication guidelines, information about supported and unsupported tools, and guidelines for structuring git repositories.

In addition to recommendations for Red Hat documentation teams, this guide provides best practices, templates, and content recommendations to upstream communities. These suggestions inform communities on how to prepare for Red Hat writers to collaborate on documentation.

[[ccg-overview]]
=== Overview

Customer Content Services (CCS) is a Red Hat team responsible for producing documentation for Red Hat customers. Because all Red Hat products have an upstream, or open source community version, it makes sense for CCS to use these upstream resources in developing guides for customers. Many programs use pieces of upstream content in the downstream documentation. This framework defines best practices for single-streaming your documentation.

In principle, single-streamed documentation will be worked on completely in the upstream and brought down to the Customer Portal wholesale. In some projects, this process eliminates the overhead of maintaining two separate repositories for documentation content. This framework guides you through the process necessary for deciding if a community is a viable single-stream partner, setting up your repositories, choosing the right tools, and more.

[[ccg-contacts]]
=== Contacts

Communicate with members of this community by signing up for our mailing list.  To sign up send an empty email to ccs-upstream-subscribe@redhat.com. If you later want to unsubscribe, send an empty email to ccs-upstream-unsubscribe@redhat.com.

To report issues or request enhancements to the Community Collaboration Guide use the link:https://github.com/redhat-documentation/community-collaboration-guide/issues[GitHub issues tool].
