[[ccg-publishing-content]]
== Publishing content

To be useful, content must be published to a public location that end users can access. There are multiple ways to publish. Some commonly used tools are described in this section.

[[ccg-asciibinder]]
=== AsciiBinder

In addition to providing a system to structure and maintain documentation for multiple brands using a single repository, AsciiBinder also provides the ability to preview and package documentation as a set of HTML files that you can publish on a website.

Run the following command to build a preview of the documentation:

[options="nowrap" subs="verbatim,quotes"]
----
$ asciibinder build
----

The output of this command is saved in the `<docs_repo_dir>/_preview/<distro>/<branch_dir_name>` directory.

Run the following command to package the documentation:

[options="nowrap" subs="verbatim,quotes"]
----
$ asciibinder package
----

The output of this command is saved in the `<docs_repo_dir>/_package/<distro>/<branch_dir_name>` directory. Each sub-directory in the `_package` represents the website content for a single brand, and can be copied to a hosting server as is.

Reference:: http://asciibinder.org/latest/guides/user_guide.html#building-the-docs[http://asciibinder.org/latest/guides/user_guide.html#building-the-docs^]

////
[[ccg-microservices]]
=== Microservices

Placeholder text.
////

[[ccg-travis-container]]
=== Using Travis CI and Asciidoctor container to publish to GitHub Pages

This publishing mechanism uses a single configuration file ``.travis.yml`` and is based on a **GitHub** + **Travis CI** + **Asciidoctor container** + **GitHub Pages** toolchain, an idea taken from https://docs.travis-ci.com/user/deployment/pages/[GitHub Pages Deployment^].

Each commit pushed to a pre-configured branch (such as ``master``, ``devel``, or ``stable``) containing a ``.travis.yml`` automatically triggers a document build, so you do not need an extra tool installed locally in order to publish an update to the document. When the Asciidoctor container running in Travis CI successfully finishes the build, Travis CI pushes the resulting HTML (and, optionally, PDF) to a deployment branch (such as ``gh-pages`` or ``publish``), and GitHub Pages then publishes the HTML (and PDF) from the deployment branch to the desired URL (for instance, ``my-project.github.io/my-document``).

This publishing mechanism is used to publish the Community Collaboration Guide from https://github.com/redhat-documentation/community-collaboration-guide[https://github.com/redhat-documentation/community-collaboration-guide^].

[[ccg-travisyml]]
==== Sample .travis.yml

Below is a sample ``.travis.yml`` file that must be placed in the root directory of your branch, from which you want to publish to GitHub Pages.

[options="nowrap" subs="verbatim,quotes"]
----
sudo: required

branches:
  only:
  - master # Branch from which to publish

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor --destination-dir=/documents/output --out-file=index.html community/master.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf --destination-dir=/documents/output --out-file=community-collaboration-guide.pdf community/master.adoc

after_error:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TOKEN # Set in travis-ci.org dashboard
  local_dir: output
  on:
    branch: master
----

//[[ccg-other]]
//=== Other

//Add if necessary.
